"use client";

import { useState } from "react";

export function PageTools({ mdPath }: { mdPath: string }) {
  const [label, setLabel] = useState("Copy page as Markdown");

  async function copyMarkdown() {
    try {
      const response = await fetch(mdPath);
      if (!response.ok) {
        throw new Error(String(response.status));
      }
      await navigator.clipboard.writeText(await response.text());
      setLabel("Copied");
    } catch {
      // The .md twins are generated by the production build.
      setLabel("Unavailable in dev");
    }
    setTimeout(() => setLabel("Copy page as Markdown"), 1500);
  }

  return (
    <span className="page-tools">
      <button className="page-tool" type="button" onClick={copyMarkdown}>
        {label}
      </button>
      <a className="page-tool" href={mdPath}>
        View raw ↗
      </a>
    </span>
  );
}
